### PR TITLE
Added Database Schema for the tool

### PR DESCRIPTION
**Pull request by MeghaSharma21**
Microtask 1 - Proposing DB schema for the tool
@eggpi please review and comment.

### CODE REVIEW

**Comment by eggpi** [comment]
Thanks! I'll come back and take a closer look tomorrow. There's also another microtask mentioned in the project description that you could think about -- basically a bit of code for grabbing the articles in a PetScan query.

**Comment by eggpi** [comment]
Nice, thank you! I think this looks very reasonable. Some of this would might change as we iterate on your proposal itself, but here's a couple of things that stand out to me and that I think weren't covered in the comments I made there:

- Shouldn't Worklist itself have a description? I believe you mentioned that in your proposal draft.
- What is the "description" of a task? Are these supposed to be filled in individually by worklist creators?
- What is Worklist's "date_updated"? Is it the Max(date_updated) across all of its tasks, or something else?
- When would an article belong to 0 tasks, or a worklist have 0 tasks?

**Comment by MeghaSharma21** [comment]
> Shouldn't Worklist itself have a description? I believe you mentioned that in your proposal draft.
Ah, my bad. I missed it here. I've updated it now.

> What is the "description" of a task? Are these supposed to be filled in individually by worklist creators?
Whenever any user adds an article to the worklist, he/she can provide the description so that it becomes clear what kind of work is needed by the article.

>  When would an article belong to 0 tasks, or a worklist have 0 tasks?
An article is simply a task that needs work. A worklist will have 0 tasks when it has no open or claimed tasks.

**Comment by eggpi** [comment]
Cool, thank you! This all seems reasonable.

> Whenever any user adds an article to the worklist, he/she can provide the description so that it becomes clear what kind of work is needed by the article.

Note that the primary thing we'd want to support is bulk-importing articles into a worklist via PetScan, text files or whatever else, in which case adding individual descriptions would be rather cumbersome. But I do agree that it makes sense to have this, and it is a good idea if we allow articles to be individually added articles.

> An article is simply a task that needs work. A worklist will have 0 tasks when it has no open or claimed tasks.

In that case I would think the worklist would still have tasks (as in, entries in the Tasks table pointing to a worklist), except all tasks would have a "completed" status. Of course if we allow people to remove articles somehow, an empty worklist could happen.

**Comment by MeghaSharma21** [comment]
> Note that the primary thing we'd want to support is bulk-importing articles into a worklist via PetScan, text files or whatever else, in which case adding individual descriptions would be rather cumbersome.
Yes, we can have that description as an optional thing so that it can be skipped for articles imported from Petscan.

Thanks for your comments. If there isn't anything else left, can you approve the PR?

**Comment by eggpi** [comment]
I guess I don't get an approve button since the repository is yours, but approved! 👍

**Pull request merged**
